# Generated by Django 2.1.4 on 2019-01-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SectionText', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontext',
            name='text_an',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
