# Generated by Django 2.1.4 on 2019-01-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SectionText', '0002_auto_20190111_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontext',
            name='nom_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sectiontext',
            name='text_fr',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
