# Generated by Django 2.1.4 on 2019-01-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologues',
            name='bio',
            field=models.TextField(blank=True, max_length=1700),
        ),
    ]
