# Generated by Django 2.1.4 on 2019-01-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologues', '0002_auto_20190104_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologues',
            name='avatar',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
