# Generated by Django 2.1.4 on 2019-01-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologues', '0003_auto_20190105_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologues',
            name='avatar',
            field=models.ImageField(upload_to='static/media/'),
        ),
    ]
