# Generated by Django 2.1.4 on 2019-01-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0005_clientele_services'),
        ('speciality', '0027_auto_20190109_1740'),
        ('psychologues', '0007_psychologues_orientation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologuesServicesofferts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientele.Clientele')),
                ('psychologue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologues.Psychologues')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speciality.SpecialityDetail')),
            ],
        ),
    ]
