# Generated by Django 2.1.4 on 2019-01-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190109_1816'),
        ('psychologues', '0008_psychologuesservicesofferts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologuesservicesofferts',
            name='specialite',
        ),
        migrations.AddField(
            model_name='psychologuesservicesofferts',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
            preserve_default=False,
        ),
    ]
