# Generated by Django 2.1.4 on 2019-01-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologues', '0009_auto_20190109_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologues',
            name='linked_in',
            field=models.URLField(blank=True),
        ),
    ]
