# Generated by Django 2.1.4 on 2019-01-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0005_clientele_services'),
        ('services', '0002_auto_20190109_1816'),
        ('psychologues', '0010_psychologues_linked_in'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PsychologuesServicesofferts',
            new_name='Competence',
        ),
    ]
