# Generated by Django 2.1.4 on 2019-01-14 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0013_auto_20190113_2237'),
        ('psychologues', '0012_auto_20190111_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='client',
        ),
        migrations.AddField(
            model_name='competence',
            name='besoin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientele.Besoin'),
            preserve_default=False,
        ),
    ]
