# Generated by Django 2.1.4 on 2019-01-14 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0002_auto_20190109_0221'),
        ('psychologues', '0013_auto_20190114_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='orientation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orientation.Orientation'),
            preserve_default=False,
        ),
    ]
