# Generated by Django 2.1.4 on 2019-01-14 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychologues', '0014_competence_orientation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ['psychologue', 'besoin', 'service']},
        ),
        migrations.AlterModelOptions(
            name='psychologue',
            options={'ordering': ['user']},
        ),
        migrations.AlterField(
            model_name='competence',
            name='orientation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orientation.Orientation'),
        ),
    ]
