# Generated by Django 2.1.4 on 2019-01-14 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychologues', '0015_auto_20190114_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologue',
            name='clientele',
        ),
        migrations.RemoveField(
            model_name='psychologue',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='psychologue',
            name='services',
        ),
        migrations.RemoveField(
            model_name='psychologue',
            name='specialities',
        ),
    ]
