# Generated by Django 2.1.4 on 2019-01-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['nom'], 'verbose_name_plural': 'Services'},
        ),
    ]
