# Generated by Django 2.1.4 on 2019-01-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0002_auto_20190108_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientele',
            options={'ordering': ['nom'], 'verbose_name_plural': 'clientels'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='clientele',
            order_with_respect_to=None,
        ),
    ]
