# Generated by Django 2.1.4 on 2019-01-08 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0003_auto_20190108_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientele',
            options={'ordering': ['nom'], 'verbose_name_plural': 'clienteles'},
        ),
    ]
