# Generated by Django 2.1.4 on 2019-01-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0036_auto_20190111_1651'),
        ('clientele', '0005_clientele_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='clientele',
            options={'ordering': ['nom_fr'], 'verbose_name_plural': 'clienteles'},
        ),
        migrations.RenameField(
            model_name='clientele',
            old_name='name',
            new_name='nom_en',
        ),
        migrations.RenameField(
            model_name='clientele',
            old_name='nom',
            new_name='nom_fr',
        ),
        migrations.AddField(
            model_name='besoin',
            name='clientele',
            field=models.ManyToManyField(to='clientele.Clientele'),
        ),
        migrations.AddField(
            model_name='besoin',
            name='probleme',
            field=models.ManyToManyField(to='speciality.Problematique'),
        ),
    ]
