# Generated by Django 2.1.4 on 2019-01-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0036_auto_20190111_1651'),
        ('clientele', '0009_auto_20190113_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientele_type', models.ManyToManyField(blank=True, to='clientele.Clientele')),
                ('probleme', models.ManyToManyField(blank=True, to='speciality.Problematique')),
            ],
        ),
    ]
