# Generated by Django 2.1.4 on 2019-01-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0036_auto_20190111_1651'),
        ('clientele', '0010_besoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='besoin',
            name='clientele_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientele.Clientele'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='besoin',
            name='probleme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='speciality.Problematique'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='besoin',
            unique_together={('clientele_type', 'probleme')},
        ),
        migrations.RemoveField(
            model_name='besoin',
            name='clientele_type',
        ),
        migrations.RemoveField(
            model_name='besoin',
            name='probleme',
        ),
    ]
