# Generated by Django 2.1.4 on 2019-01-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0014_ressource'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='desc_en',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ressource',
            name='desc_fr',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ressource',
            name='nom_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ressource',
            name='nom_fr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
