# Generated by Django 2.1.4 on 2019-01-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0015_auto_20190114_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='besoin',
            name='ressource',
            field=models.ManyToManyField(to='clientele.Ressource'),
        ),
    ]
