# Generated by Django 2.1.4 on 2018-12-28 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0005_auto_20181228_2150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialityDetails',
            new_name='SpecialityDetail',
        ),
        migrations.AlterModelOptions(
            name='specialitydetail',
            options={'verbose_name_plural': 'speciality details'},
        ),
        migrations.AlterField(
            model_name='specialitydetail',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speciality.Speciality'),
        ),
    ]
