# Generated by Django 2.1.4 on 2019-01-08 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0023_auto_20190108_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'ordering': ['name'], 'verbose_name_plural': 'specialities'},
        ),
        migrations.AlterModelOptions(
            name='specialitydetail',
            options={'ordering': ['name'], 'verbose_name_plural': 'speciality details'},
        ),
        migrations.AlterField(
            model_name='specialitydetail',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speciality.Speciality'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='speciality',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='specialitydetail',
            order_with_respect_to=None,
        ),
    ]
