# Generated by Django 2.1.4 on 2019-01-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0027_auto_20190109_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialitydetail',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speciality.Speciality'),
        ),
    ]
