# Generated by Django 2.1.4 on 2019-01-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0032_auto_20190111_1556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='speciality',
            new_name='ProblematiqueType',
        ),
    ]
