# Generated by Django 2.1.4 on 2019-01-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0034_auto_20190111_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problematiquetype',
            options={'ordering': ['nom_fr'], 'verbose_name_plural': 'Type de Problématique'},
        ),
        migrations.RenameField(
            model_name='problematiquetype',
            old_name='name',
            new_name='nom_fr',
        ),
    ]
