# Generated by Django 2.1.4 on 2019-01-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychologues', '0012_auto_20190111_1556'),
        ('speciality', '0035_auto_20190111_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialityDetail',
            new_name='Problematique',
        ),
        migrations.AlterModelOptions(
            name='problematique',
            options={'ordering': ['nom_fr'], 'verbose_name_plural': 'Problematiques'},
        ),
        migrations.RenameField(
            model_name='problematique',
            old_name='description',
            new_name='desc_fr',
        ),
        migrations.RenameField(
            model_name='problematique',
            old_name='name',
            new_name='nom_fr',
        ),
    ]
