# Generated by Django 2.1.4 on 2019-01-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('desc_fr', models.TextField(blank=True, max_length=1000)),
                ('desc_ang', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
