# Generated by Django 2.1.4 on 2019-01-09 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orientation',
            options={'ordering': ['nom'], 'verbose_name_plural': 'Orientations'},
        ),
    ]
